<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Momoka.Core.Tests.Plugins.RouterBad</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <IsPlugin>true</IsPlugin>
    <PluginId>routerbad</PluginId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../Momoka.Core/Momoka.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="plugin.toml" />
  </ItemGroup>

</Project>
